
services:

  auth_service:
    build:
      context: .  
      dockerfile: Dockerfile
    ports:
      - "8083:8083" 
      - "9090:9090"
    env_file:
      - .env
    environment:
      - DB_DSN=${DSN}
      - REDIS_PORT=${REDIS_PORT}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - redis  
    networks:
      - app-base-server_app-network  



  redis:
    image: redis:7.4-alpine  
    ports:
      - "6381:6379"
    networks:
      - app-base-server_app-network 



volumes:
  postgres_data:
    driver: local


networks:
  app-base-server_app-network:
    external: true
