// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: auth_service.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_auth_service_proto protoreflect.FileDescriptor

const file_auth_service_proto_rawDesc = "" +
	"\n" +
	"\x12auth_service.proto\x12\x02pb\x1a\x17rpc_register_user.proto\x1a\x14rpc_login_user.proto\x1a\x15rpc_update_user.proto\x1a\x16rpc_verify_email.proto\x1a\x16rpc_verify_token.proto\x1a\x15rpc_verify_role.proto\x1a\x1cgoogle/api/annotations.proto2\xb2\x04\n" +
	"\vAuthService\x12b\n" +
	"\fRegisterUser\x12\x17.pb.RegisterUserRequest\x1a\x1b.pb.RegisterResponsePayload\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/register_user\x12V\n" +
	"\tLoginUser\x12\x14.pb.LoginUserRequest\x1a\x18.pb.LoginResponsePayload\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/login_user\x12W\n" +
	"\n" +
	"UpdateUser\x12\x15.pb.UpdateUserRequest\x1a\x16.pb.UpdateUserResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*2\x0f/v1/update_user\x12X\n" +
	"\vVerifyEmail\x12\x16.pb.VerifyEmailRequest\x1a\x17.pb.VerifyEmailResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/verify_email\x12[\n" +
	"\vVerifyToken\x12\x16.pb.VerifyTokenRequest\x1a\x17.pb.VerifyTokenResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/verify_token\x12W\n" +
	"\n" +
	"VerifyRole\x12\x15.pb.VerifyRoleRequest\x1a\x16.pb.VerifyRoleResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/verify_roleB*Z(github.com/Iowel/app-auth-service/pkg/pbb\x06proto3"

var file_auth_service_proto_goTypes = []any{
	(*RegisterUserRequest)(nil),     // 0: pb.RegisterUserRequest
	(*LoginUserRequest)(nil),        // 1: pb.LoginUserRequest
	(*UpdateUserRequest)(nil),       // 2: pb.UpdateUserRequest
	(*VerifyEmailRequest)(nil),      // 3: pb.VerifyEmailRequest
	(*VerifyTokenRequest)(nil),      // 4: pb.VerifyTokenRequest
	(*VerifyRoleRequest)(nil),       // 5: pb.VerifyRoleRequest
	(*RegisterResponsePayload)(nil), // 6: pb.RegisterResponsePayload
	(*LoginResponsePayload)(nil),    // 7: pb.LoginResponsePayload
	(*UpdateUserResponse)(nil),      // 8: pb.UpdateUserResponse
	(*VerifyEmailResponse)(nil),     // 9: pb.VerifyEmailResponse
	(*VerifyTokenResponse)(nil),     // 10: pb.VerifyTokenResponse
	(*VerifyRoleResponse)(nil),      // 11: pb.VerifyRoleResponse
}
var file_auth_service_proto_depIdxs = []int32{
	0,  // 0: pb.AuthService.RegisterUser:input_type -> pb.RegisterUserRequest
	1,  // 1: pb.AuthService.LoginUser:input_type -> pb.LoginUserRequest
	2,  // 2: pb.AuthService.UpdateUser:input_type -> pb.UpdateUserRequest
	3,  // 3: pb.AuthService.VerifyEmail:input_type -> pb.VerifyEmailRequest
	4,  // 4: pb.AuthService.VerifyToken:input_type -> pb.VerifyTokenRequest
	5,  // 5: pb.AuthService.VerifyRole:input_type -> pb.VerifyRoleRequest
	6,  // 6: pb.AuthService.RegisterUser:output_type -> pb.RegisterResponsePayload
	7,  // 7: pb.AuthService.LoginUser:output_type -> pb.LoginResponsePayload
	8,  // 8: pb.AuthService.UpdateUser:output_type -> pb.UpdateUserResponse
	9,  // 9: pb.AuthService.VerifyEmail:output_type -> pb.VerifyEmailResponse
	10, // 10: pb.AuthService.VerifyToken:output_type -> pb.VerifyTokenResponse
	11, // 11: pb.AuthService.VerifyRole:output_type -> pb.VerifyRoleResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_auth_service_proto_init() }
func file_auth_service_proto_init() {
	if File_auth_service_proto != nil {
		return
	}
	file_rpc_register_user_proto_init()
	file_rpc_login_user_proto_init()
	file_rpc_update_user_proto_init()
	file_rpc_verify_email_proto_init()
	file_rpc_verify_token_proto_init()
	file_rpc_verify_role_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_service_proto_rawDesc), len(file_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_service_proto_goTypes,
		DependencyIndexes: file_auth_service_proto_depIdxs,
	}.Build()
	File_auth_service_proto = out.File
	file_auth_service_proto_goTypes = nil
	file_auth_service_proto_depIdxs = nil
}
