// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: rpc_login_user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRequest) Reset() {
	*x = LoginUserRequest{}
	mi := &file_rpc_login_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest) ProtoMessage() {}

func (x *LoginUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_login_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRequest.ProtoReflect.Descriptor instead.
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return file_rpc_login_user_proto_rawDescGZIP(), []int{0}
}

func (x *LoginUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponsePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         bool                   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Token         *Token                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponsePayload) Reset() {
	*x = LoginResponsePayload{}
	mi := &file_rpc_login_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponsePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponsePayload) ProtoMessage() {}

func (x *LoginResponsePayload) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_login_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponsePayload.ProtoReflect.Descriptor instead.
func (*LoginResponsePayload) Descriptor() ([]byte, []int) {
	return file_rpc_login_user_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponsePayload) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *LoginResponsePayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginResponsePayload) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plaintext     string                 `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	Userid        int64                  `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`
	Hash          []byte                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Expiry        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Scope         string                 `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_rpc_login_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_login_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_rpc_login_user_proto_rawDescGZIP(), []int{2}
}

func (x *Token) GetPlaintext() string {
	if x != nil {
		return x.Plaintext
	}
	return ""
}

func (x *Token) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *Token) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Token) GetExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiry
	}
	return nil
}

func (x *Token) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Token) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_rpc_login_user_proto protoreflect.FileDescriptor

const file_rpc_login_user_proto_rawDesc = "" +
	"\n" +
	"\x14rpc_login_user.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"D\n" +
	"\x10LoginUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"g\n" +
	"\x14LoginResponsePayload\x12\x14\n" +
	"\x05error\x18\x01 \x01(\bR\x05error\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\x05token\x18\x03 \x01(\v2\t.pb.TokenR\x05token\"\xaf\x01\n" +
	"\x05Token\x12\x1c\n" +
	"\tplaintext\x18\x01 \x01(\tR\tplaintext\x12\x16\n" +
	"\x06userid\x18\x02 \x01(\x03R\x06userid\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\fR\x04hash\x122\n" +
	"\x06expiry\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x06expiry\x12\x14\n" +
	"\x05scope\x18\x05 \x01(\tR\x05scope\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04roleB*Z(github.com/Iowel/app-auth-service/pkg/pbb\x06proto3"

var (
	file_rpc_login_user_proto_rawDescOnce sync.Once
	file_rpc_login_user_proto_rawDescData []byte
)

func file_rpc_login_user_proto_rawDescGZIP() []byte {
	file_rpc_login_user_proto_rawDescOnce.Do(func() {
		file_rpc_login_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_login_user_proto_rawDesc), len(file_rpc_login_user_proto_rawDesc)))
	})
	return file_rpc_login_user_proto_rawDescData
}

var file_rpc_login_user_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rpc_login_user_proto_goTypes = []any{
	(*LoginUserRequest)(nil),      // 0: pb.LoginUserRequest
	(*LoginResponsePayload)(nil),  // 1: pb.LoginResponsePayload
	(*Token)(nil),                 // 2: pb.Token
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_rpc_login_user_proto_depIdxs = []int32{
	2, // 0: pb.LoginResponsePayload.token:type_name -> pb.Token
	3, // 1: pb.Token.expiry:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_login_user_proto_init() }
func file_rpc_login_user_proto_init() {
	if File_rpc_login_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_login_user_proto_rawDesc), len(file_rpc_login_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_login_user_proto_goTypes,
		DependencyIndexes: file_rpc_login_user_proto_depIdxs,
		MessageInfos:      file_rpc_login_user_proto_msgTypes,
	}.Build()
	File_rpc_login_user_proto = out.File
	file_rpc_login_user_proto_goTypes = nil
	file_rpc_login_user_proto_depIdxs = nil
}
