// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: rpc_register_user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_rpc_register_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_register_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_rpc_register_user_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponsePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         bool                   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponsePayload) Reset() {
	*x = RegisterResponsePayload{}
	mi := &file_rpc_register_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponsePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponsePayload) ProtoMessage() {}

func (x *RegisterResponsePayload) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_register_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponsePayload.ProtoReflect.Descriptor instead.
func (*RegisterResponsePayload) Descriptor() ([]byte, []int) {
	return file_rpc_register_user_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponsePayload) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *RegisterResponsePayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rpc_register_user_proto protoreflect.FileDescriptor

const file_rpc_register_user_proto_rawDesc = "" +
	"\n" +
	"\x17rpc_register_user.proto\x12\x02pb\"[\n" +
	"\x13RegisterUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"I\n" +
	"\x17RegisterResponsePayload\x12\x14\n" +
	"\x05error\x18\x01 \x01(\bR\x05error\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB*Z(github.com/Iowel/app-auth-service/pkg/pbb\x06proto3"

var (
	file_rpc_register_user_proto_rawDescOnce sync.Once
	file_rpc_register_user_proto_rawDescData []byte
)

func file_rpc_register_user_proto_rawDescGZIP() []byte {
	file_rpc_register_user_proto_rawDescOnce.Do(func() {
		file_rpc_register_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_register_user_proto_rawDesc), len(file_rpc_register_user_proto_rawDesc)))
	})
	return file_rpc_register_user_proto_rawDescData
}

var file_rpc_register_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_register_user_proto_goTypes = []any{
	(*RegisterUserRequest)(nil),     // 0: pb.RegisterUserRequest
	(*RegisterResponsePayload)(nil), // 1: pb.RegisterResponsePayload
}
var file_rpc_register_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_register_user_proto_init() }
func file_rpc_register_user_proto_init() {
	if File_rpc_register_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_register_user_proto_rawDesc), len(file_rpc_register_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_register_user_proto_goTypes,
		DependencyIndexes: file_rpc_register_user_proto_depIdxs,
		MessageInfos:      file_rpc_register_user_proto_msgTypes,
	}.Build()
	File_rpc_register_user_proto = out.File
	file_rpc_register_user_proto_goTypes = nil
	file_rpc_register_user_proto_depIdxs = nil
}
